# Site wide configuration

title: Ipaler.com
description: "Ipaler.com, A lightweight site starter for Jekyll"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //ipaler.com

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: ipaler
  web: http://ipaler.com
  email: wangmingzhong.cncq@gmail.com
  twitter: wangmingzhong
  bio: "Just another boring, tattooed, time traveling designer."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +wangmingzhong
    ad-client: ca-pub-7328585512091257
    ad-slot: 3049671934
  disqus-shortname: ipaler


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]