markdown: rdiscount
pygments: true
permalink: /posts/:title.html
auto: true
rdiscount:
  extensions: [smart]

title: Ipaler.com
author:
  name: Ipaler.com
  email: wangmingzhong.cncq@gmail.com
  github: ipaler
  twitter: wangmingzhong

production_url: http://ipaler.com/